// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSpN6GuPrGuB343WeLbZ-vdc12d82QwWw',
    appId: '1:8009482651:web:c717bb7bbef326d640a13e',
    messagingSenderId: '8009482651',
    projectId: 'jaja-cf083',
    authDomain: 'jaja-cf083.firebaseapp.com',
    storageBucket: 'jaja-cf083.appspot.com',
    measurementId: 'G-ENK86QZ4S9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeNwrZQ7h58bovSAdPw69e7xb0J9igfLk',
    appId: '1:8009482651:android:14fd0a0efbf583a140a13e',
    messagingSenderId: '8009482651',
    projectId: 'jaja-cf083',
    storageBucket: 'jaja-cf083.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOaCxojixoMi_igLgs8d8H7DnHzI2Hfls',
    appId: '1:8009482651:ios:659e63f1ee85591740a13e',
    messagingSenderId: '8009482651',
    projectId: 'jaja-cf083',
    storageBucket: 'jaja-cf083.appspot.com',
    iosClientId: '8009482651-4jqv388plc4i1q9fnl0bgfft6qom5c9e.apps.googleusercontent.com',
    iosBundleId: 'com.jaja.voiceshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOaCxojixoMi_igLgs8d8H7DnHzI2Hfls',
    appId: '1:8009482651:ios:659e63f1ee85591740a13e',
    messagingSenderId: '8009482651',
    projectId: 'jaja-cf083',
    storageBucket: 'jaja-cf083.appspot.com',
    iosClientId: '8009482651-4jqv388plc4i1q9fnl0bgfft6qom5c9e.apps.googleusercontent.com',
    iosBundleId: 'com.jaja.voiceshare',
  );
}
